# Chicago public schools : Student Clustering

## Topic

## Objective

## Summary

## Importing libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime as dt
sns.set(rc = {'figure.figsize':(15,8)})

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

from sklearn.model_selection import train_test_split
from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN
from sklearn.mixture import GaussianMixture

from sklearn.metrics import silhouette_score
from yellowbrick.cluster import SilhouetteVisualizer

from sklearn import metrics
from sklearn.metrics import davies_bouldin_score

## Uploading the dataset

In [2]:
cards = pd.read_csv(r'C:\Users\imane\OneDrive\Desktop\Chicago_Public_schools\Chicago-RP-2011-2012-1.csv', sep =",")
cards.head()

,School ID,Name of School,"Elementary, Middle, or High School",Street Address,City,State,ZIP Code,Phone Number,Link,Network Manager,...,RCDTS Code,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,Community Area Number,Community Area Name,Ward,Police District,Location
0,610038,Abraham Lincoln Elementary School,ES,615 W Kemper Pl,Chicago,IL,60614,(773) 534-5720,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,150000000000000,1171699.458,1915829.428,41.924497,-87.644522,7,LINCOLN PARK,43,18,"(41.92449696, -87.64452163)"
1,610281,Adam Clayton Powell Paideia Community Academy ...,ES,7511 S South Shore Dr,Chicago,IL,60649,(773) 535-6650,http://schoolreports.cps.edu/SchoolProgressRep...,Skyway Elementary Network,...,150000000000000,1196129.985,1856209.466,41.760324,-87.556736,43,SOUTH SHORE,7,4,"(41.76032435, -87.55673627)"
2,610185,Adlai E Stevenson Elementary School,ES,8010 S Kostner Ave,Chicago,IL,60652,(773) 535-2280,http://schoolreports.cps.edu/SchoolProgressRep...,Midway Elementary Network,...,150000000000000,1148427.165,1851012.215,41.747111,-87.731702,70,ASHBURN,13,8,"(41.74711093, -87.73170248)"
3,609993,Agustin Lara Elementary Academy,ES,4619 S Wolcott Ave,Chicago,IL,60609,(773) 535-4389,http://schoolreports.cps.edu/SchoolProgressRep...,Pershing Elementary Network,...,150000000000000,1164504.290,1873959.199,41.809757,-87.672145,61,NEW CITY,20,9,"(41.8097569, -87.6721446)"
4,610513,Air Force Academy High School,HS,3630 S Wells St,Chicago,IL,60609,(773) 535-1590,http://schoolreports.cps.edu/SchoolProgressRep...,Southwest Side High School Network,...,150000000000000,1175177.622,1880745.126,41.828146,-87.632794,34,ARMOUR SQUARE,11,9,"(41.82814609, -87.63279369)"

In [3]:
cards.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566 entries, 0 to 565
Data columns (total 79 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   School ID                                          566 non-null    int64
 1   Name of School                                     566 non-null    object
 2   Elementary, Middle, or High School                 566 non-null    object
 3   Street Address                                     566 non-null    object
 4   City                                               566 non-null    object
 5   State                                              566 non-null    object
 6   ZIP Code                                           566 non-null    int64
 7   Phone Number                                       566 non-null    object
 8   Link                                               565 non-null    object
 9   Network Manager                                    566 non-null    object
 10  Collaborative Name                                 566 non-null    object
 11  Adequate Yearly Progress Made?                     566 non-null    object
 12  Track Schedule                                     566 non-null    object
 13  CPS Performance Policy Status                      566 non-null    object
 14  CPS Performance Policy Level                       566 non-null    object
 15  Healthy Schools Certified?                         566 non-null    object
 16  Safety Icon                                        566 non-null    object
 17  Safety Score                                       513 non-null    float64
 18  Family Involvement Icon                            566 non-null    object
 19  Family Involvement Score                           566 non-null    object
 20  Environment Icon                                   566 non-null    object
 21  Environment Score                                  513 non-null    float64
 22  Instruction Icon                                   566 non-null    object
 23  Instruction Score                                  513 non-null    float64
 24  Leaders Icon                                       566 non-null    object
 25  Leaders Score                                      566 non-null    object
 26  Teachers Icon                                      566 non-null    object
 27  Teachers Score                                     566 non-null    object
 28  Parent Engagement Icon                             566 non-null    object
 29  Parent Engagement Score                            566 non-null    object
 30  Parent Environment Icon                            566 non-null    object
 31  Parent Environment Score                           566 non-null    object
 32  Average Student Attendance                         565 non-null    object
 33  Rate of Misconducts (per 100 students)             566 non-null    float64
 34  Average Teacher Attendance                         566 non-null    object
 35  Individualized Education Program Compliance Rate   566 non-null    object
 36  Pk-2 Literacy %                                    566 non-null    object
 37  Pk-2 Math %                                        566 non-null    object
 38  Gr3-5 Grade Level Math %                           566 non-null    object
 39  Gr3-5 Grade Level Read %                           566 non-null    object
 40  Gr3-5 Keep Pace Read %                             566 non-null    object
 41  Gr3-5 Keep Pace Math %                             566 non-null    object
 42  Gr6-8 Grade Level Math %                           566 non-null    object
 43  Gr6-8 Grade Level Read %                           566 non-null    object
 44  Gr6-8 Keep Pace Math%                              566 non-null    object
 45  Gr6-8 Keep Pace Read %                             566 non-null    object
 46  Gr-8 Explore Math %                                566 non-null    object
 47  Gr-8 Explore Read %                                566 non-null    object
 48  ISAT Exceeding Math %                              476 non-null    float64
 49  ISAT Exceeding Reading %                           476 non-null    float64
 50  ISAT Value Add Math                                468 non-null    float64
 51  ISAT Value Add Read                                468 non-null    float64
 52  ISAT Value Add Color Math                          566 non-null    object
 53  ISAT Value Add Color Read                          566 non-null    object
 54  Students Taking  Algebra %                         566 non-null    object
 55  Students Passing  Algebra %                        566 non-null    object
 56  9th Grade EXPLORE (2009)                           566 non-null    object
 57  9th Grade EXPLORE (2010)                           566 non-null    object
 58  10th Grade PLAN (2009)                             566 non-null    object
 59  10th Grade PLAN (2010)                             566 non-null    object
 60  Net Change EXPLORE and PLAN                        566 non-null    object
 61  11th Grade Average ACT (2011)                      566 non-null    object
 62  Net Change PLAN and ACT                            566 non-null    object
 63  College Eligibility %                              566 non-null    object
 64  Graduation Rate %                                  566 non-null    object
 65  College Enrollment Rate %                          566 non-null    object
 66  College Enrollment (number of students)            566 non-null    int64
 67  General Services Route                             566 non-null    int64
 68  Freshman on Track Rate %                           566 non-null    object
 69  RCDTS Code                                         566 non-null    int64
 70  X_COORDINATE                                       566 non-null    float64
 71  Y_COORDINATE                                       566 non-null    float64
 72  Latitude                                           566 non-null    float64
 73  Longitude                                          566 non-null    float64
 74  Community Area Number                              566 non-null    int64
 75  Community Area Name                                566 non-null    object
 76  Ward                                               566 non-null    int64
 77  Police District                                    566 non-null    int64
 78  Location                                           566 non-null    object
dtypes: float64(12), int64(8), object(59)
memory usage: 349.5+ KB

In [7]:
cards.isnull().sum()

School ID                             0
Name of School                        0
Elementary, Middle, or High School    0
Street Address                        0
City                                  0
                                     ..
Community Area Number                 0
Community Area Name                   0
Ward                                  0
Police District                       0
Location                              0
Length: 79, dtype: int64